# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('idaccessories', models.IntegerField(db_column='idAccessories', primary_key=True, serialize=False)),
                ('nameac', models.CharField(blank=True, db_column='nameAc', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Accessories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('idcategories', models.IntegerField(db_column='idCategories', primary_key=True, serialize=False)),
                ('nameca', models.CharField(blank=True, db_column='nameCa', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChAc',
            fields=[
                ('idch_ac', models.IntegerField(db_column='idCh_Ac', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Ch_Ac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('idcharacters', models.AutoField(db_column='idCharacters', primary_key=True, serialize=False)),
                ('namech', models.CharField(blank=True, db_column='nameCh', max_length=45, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'Characters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Containers',
            fields=[
                ('idcontainers', models.IntegerField(db_column='idContainers', primary_key=True, serialize=False)),
                ('nameco', models.CharField(blank=True, db_column='nameCo', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Containers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('iddrinks', models.IntegerField(db_column='idDrinks', primary_key=True, serialize=False)),
                ('namedr', models.CharField(blank=True, db_column='nameDr', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Drinks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enemies',
            fields=[
                ('idenemies', models.IntegerField(db_column='idEnemies', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Enemies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('idfoods', models.IntegerField(db_column='idFoods', primary_key=True, serialize=False)),
                ('namefo', models.CharField(blank=True, db_column='nameFo', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Foods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('idfriends', models.IntegerField(db_column='idFriends', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Friends',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('idjobs', models.IntegerField(db_column='idJobs', primary_key=True, serialize=False)),
                ('namejo', models.CharField(blank=True, db_column='nameJo', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('idrole', models.IntegerField(db_column='idRole', primary_key=True, serialize=False)),
                ('namero', models.CharField(blank=True, db_column='nameRo', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scenarios',
            fields=[
                ('idscenarios', models.IntegerField(db_column='idScenarios', primary_key=True, serialize=False)),
                ('namesc', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Scenarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('idspecies', models.IntegerField(db_column='idSpecies', primary_key=True, serialize=False)),
                ('namesp', models.CharField(blank=True, db_column='nameSp', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Species',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StCh',
            fields=[
                ('idst_ch', models.IntegerField(db_column='idSt_Ch', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'St_Ch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('idstory', models.IntegerField(db_column='idStory', primary_key=True, serialize=False)),
                ('namest', models.CharField(blank=True, db_column='nameSt', max_length=45, null=True)),
                ('script', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Story',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('idtools', models.IntegerField(db_column='idTools', primary_key=True, serialize=False)),
                ('nameto', models.CharField(blank=True, db_column='nameTo', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Tools',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('idtype', models.IntegerField(db_column='idType', primary_key=True, serialize=False)),
                ('namety', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Type',
                'managed': False,
            },
        ),
    ]
