# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChTi',
            fields=[
                ('idch_ti', models.IntegerField(db_column='idCh_Ti', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Ch_Ti',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dance',
            fields=[
                ('idda', models.AutoField(db_column='idDa', primary_key=True, serialize=False)),
                ('nameda', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Dance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FullSt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('idge', models.AutoField(db_column='idGe', primary_key=True, serialize=False)),
                ('namege', models.CharField(blank=True, db_column='nameGe', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Gender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticks',
            fields=[
                ('idti', models.AutoField(db_column='idTi', primary_key=True, serialize=False)),
                ('tickscol', models.CharField(blank=True, db_column='Tickscol', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Ticks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('idwe', models.AutoField(db_column='idWe', primary_key=True, serialize=False)),
                ('namewe', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Weapons',
                'managed': False,
            },
        ),
    ]
