# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_chti_dance_fullst_gender_ticks_weapons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('idplace', models.AutoField(db_column='idPlace', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Place',
                'managed': False,
            },
        ),
    ]
